--
-- PostgreSQL database dump
--

\restrict daO011BmuzbO6RJ6BnAj5esd1LEKjZgIDcaPXRDbkNRDsEH2i5jlp2FvKR1aSFk

-- Dumped from database version 16.14 (Homebrew)
-- Dumped by pg_dump version 16.14 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: announcements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.announcements (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_pinned boolean NOT NULL,
    priority character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    author_id bigint NOT NULL,
    startup_id bigint NOT NULL,
    CONSTRAINT announcements_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'NORMAL'::character varying, 'HIGH'::character varying])::text[])))
);


ALTER TABLE public.announcements OWNER TO postgres;

--
-- Name: announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.application_status_history (
    id bigint NOT NULL,
    changed_at timestamp(6) without time zone NOT NULL,
    comments character varying(1000),
    status character varying(255) NOT NULL,
    application_id bigint NOT NULL,
    changed_by_user_id bigint NOT NULL,
    CONSTRAINT application_status_history_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SHORTLISTED'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'WITHDRAWN'::character varying, 'REVOKED'::character varying])::text[])))
);


ALTER TABLE public.application_status_history OWNER TO postgres;

--
-- Name: application_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.application_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: call_analytics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.call_analytics (
    id bigint NOT NULL,
    audio_constraint_supported boolean,
    average_bitrate double precision,
    average_jitter double precision,
    average_packet_loss double precision,
    average_rtt double precision,
    browser character varying(255),
    cpu_usage double precision,
    device_changes integer,
    ice_restarts integer,
    max_bitrate double precision,
    max_jitter double precision,
    max_packet_loss double precision,
    max_rtt double precision,
    memory_usage double precision,
    mic_permission_failures integer,
    min_bitrate double precision,
    mute_count integer,
    os character varying(255),
    reconnections integer,
    selected_candidate_type character varying(255),
    stun_used boolean,
    turn_used boolean,
    call_log_id bigint NOT NULL
);


ALTER TABLE public.call_analytics OWNER TO postgres;

--
-- Name: call_analytics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.call_analytics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.call_analytics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: call_log_deletions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.call_log_deletions (
    call_id bigint NOT NULL,
    user_id bigint
);


ALTER TABLE public.call_log_deletions OWNER TO postgres;

--
-- Name: call_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.call_logs (
    id bigint NOT NULL,
    duration_seconds integer,
    started_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    uuid uuid NOT NULL,
    caller_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    workspace_id bigint
);


ALTER TABLE public.call_logs OWNER TO postgres;

--
-- Name: call_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.call_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.call_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_members (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone,
    role character varying(255) NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT chat_members_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);


ALTER TABLE public.chat_members OWNER TO postgres;

--
-- Name: chat_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message_deletions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message_deletions (
    message_id bigint NOT NULL,
    user_id bigint
);


ALTER TABLE public.chat_message_deletions OWNER TO postgres;

--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    is_deleted boolean NOT NULL,
    is_edited boolean NOT NULL,
    is_pinned boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid uuid NOT NULL,
    is_voice_note boolean DEFAULT false NOT NULL,
    voice_note_duration integer,
    voice_note_waveform text,
    reply_to_id bigint,
    room_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.chat_messages OWNER TO postgres;

--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_notifications (
    id bigint NOT NULL,
    action_data character varying(255),
    content text,
    created_at timestamp(6) without time zone,
    is_deleted boolean NOT NULL,
    is_read boolean NOT NULL,
    type character varying(255) NOT NULL,
    uuid uuid NOT NULL,
    message_id bigint,
    recipient_id bigint NOT NULL,
    room_id bigint,
    sender_id bigint,
    startup_id bigint
);


ALTER TABLE public.chat_notifications OWNER TO postgres;

--
-- Name: chat_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_rooms (
    id bigint NOT NULL,
    color_theme character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    icon_url character varying(255),
    is_archived boolean NOT NULL,
    name character varying(255),
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid uuid NOT NULL,
    visibility character varying(255),
    startup_id bigint NOT NULL,
    CONSTRAINT chat_rooms_type_check CHECK (((type)::text = ANY ((ARRAY['GENERAL'::character varying, 'GROUP'::character varying, 'PRIVATE'::character varying])::text[])))
);


ALTER TABLE public.chat_rooms OWNER TO postgres;

--
-- Name: chat_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_settings (
    id bigint NOT NULL,
    allow_attachments boolean NOT NULL,
    allow_links boolean NOT NULL,
    room_id bigint NOT NULL
);


ALTER TABLE public.chat_settings OWNER TO postgres;

--
-- Name: chat_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.custom_roles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    uuid uuid NOT NULL,
    startup_id bigint NOT NULL
);


ALTER TABLE public.custom_roles OWNER TO postgres;

--
-- Name: custom_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.custom_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_offers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_offers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid uuid NOT NULL,
    founder_id bigint NOT NULL,
    startup_id bigint NOT NULL,
    talent_id bigint NOT NULL
);


ALTER TABLE public.job_offers OWNER TO postgres;

--
-- Name: job_offers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meeting_chats (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    uuid uuid NOT NULL,
    meeting_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.meeting_chats OWNER TO postgres;

--
-- Name: meeting_chats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meeting_chats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_chats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_participants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meeting_participants (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone,
    left_at timestamp(6) without time zone,
    role character varying(255) NOT NULL,
    meeting_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT meeting_participants_role_check CHECK (((role)::text = ANY ((ARRAY['HOST'::character varying, 'CO_HOST'::character varying, 'PARTICIPANT'::character varying])::text[])))
);


ALTER TABLE public.meeting_participants OWNER TO postgres;

--
-- Name: meeting_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meeting_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meetings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meetings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    ended_at timestamp(6) without time zone,
    scheduled_end_time timestamp(6) without time zone,
    scheduled_start_time timestamp(6) without time zone,
    started_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid uuid NOT NULL,
    creator_id bigint NOT NULL,
    startup_id bigint NOT NULL,
    CONSTRAINT meetings_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT meetings_type_check CHECK (((type)::text = ANY ((ARRAY['INSTANT'::character varying, 'SCHEDULED'::character varying])::text[])))
);


ALTER TABLE public.meetings OWNER TO postgres;

--
-- Name: meetings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_attachments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    file_name character varying(255) NOT NULL,
    file_size bigint,
    file_type character varying(255) NOT NULL,
    file_url character varying(255) NOT NULL,
    uuid uuid NOT NULL,
    message_id bigint NOT NULL
);


ALTER TABLE public.message_attachments OWNER TO postgres;

--
-- Name: message_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_reactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_reactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    emoji character varying(255) NOT NULL,
    message_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.message_reactions OWNER TO postgres;

--
-- Name: message_reactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message_reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_reactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_read_receipts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_read_receipts (
    id bigint NOT NULL,
    read_at timestamp(6) without time zone NOT NULL,
    last_read_message_id bigint NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.message_read_receipts OWNER TO postgres;

--
-- Name: message_read_receipts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message_read_receipts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_read_receipts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_statuses (
    id bigint NOT NULL,
    delivered_at timestamp(6) without time zone,
    read_at timestamp(6) without time zone,
    message_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.message_statuses OWNER TO postgres;

--
-- Name: message_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: privacy_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.privacy_settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    contact_visibility character varying(20) NOT NULL,
    profile_visibility character varying(20) NOT NULL,
    show_startup_profile boolean,
    user_id bigint NOT NULL
);


ALTER TABLE public.privacy_settings OWNER TO postgres;

--
-- Name: privacy_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.privacy_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.privacy_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    role_id bigint NOT NULL,
    permission character varying(255)
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- Name: startup_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.startup_applications (
    id bigint NOT NULL,
    achievements character varying(255),
    additional_notes character varying(2000),
    available_start_date character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    current_occupation character varying(255),
    github_url character varying(255),
    hours_available character varying(255),
    introduction character varying(1000),
    linkedin_url character varying(255),
    open_source_contributions character varying(255),
    personal_website_url character varying(255),
    portfolio_url character varying(255),
    preferred_role character varying(255),
    preferred_working_style character varying(255),
    previous_startup_experience character varying(255),
    resume_url character varying(255),
    skills character varying(255),
    status character varying(255) NOT NULL,
    technologies_known character varying(255),
    updated_at timestamp(6) without time zone,
    uuid uuid NOT NULL,
    why_join character varying(2000),
    why_right_fit character varying(2000),
    years_experience character varying(255),
    startup_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT startup_applications_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SHORTLISTED'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'WITHDRAWN'::character varying, 'REVOKED'::character varying])::text[])))
);


ALTER TABLE public.startup_applications OWNER TO postgres;

--
-- Name: startup_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.startup_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.startup_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: startup_attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.startup_attachments (
    id bigint NOT NULL,
    file_name character varying(255),
    type character varying(255) NOT NULL,
    url character varying(255) NOT NULL,
    startup_id bigint NOT NULL,
    CONSTRAINT startup_attachments_type_check CHECK (((type)::text = ANY ((ARRAY['PITCH_DECK'::character varying, 'PROTOTYPE'::character varying, 'DEMO_LINK'::character varying, 'WEBSITE'::character varying, 'GITHUB'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.startup_attachments OWNER TO postgres;

--
-- Name: startup_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.startup_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.startup_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: startup_bookmarks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.startup_bookmarks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    startup_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.startup_bookmarks OWNER TO postgres;

--
-- Name: startup_bookmarks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.startup_bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.startup_bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: startup_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.startup_roles (
    id bigint NOT NULL,
    role_name character varying(255) NOT NULL,
    startup_id bigint NOT NULL
);


ALTER TABLE public.startup_roles OWNER TO postgres;

--
-- Name: startup_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.startup_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.startup_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: startup_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.startup_skills (
    id bigint NOT NULL,
    skill_name character varying(255) NOT NULL,
    startup_id bigint NOT NULL
);


ALTER TABLE public.startup_skills OWNER TO postgres;

--
-- Name: startup_skills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.startup_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.startup_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: startup_views; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.startup_views (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    startup_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.startup_views OWNER TO postgres;

--
-- Name: startup_views_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.startup_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.startup_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: startups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.startups (
    id bigint NOT NULL,
    business_model text,
    city character varying(255),
    commitment_type character varying(255),
    cover_url character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    current_progress text,
    detailed_description text,
    equity_available character varying(255),
    equity_percentage character varying(255),
    expected_team_size character varying(255),
    future_goals text,
    industry character varying(255),
    is_deleted boolean NOT NULL,
    launch_goal character varying(255),
    logo_url character varying(255),
    max_members integer,
    mission text,
    name character varying(255) NOT NULL,
    pitch text,
    problem_statement text,
    revenue_model text,
    roadmap text,
    solution text,
    stage character varying(255),
    status character varying(255) NOT NULL,
    tagline text,
    target_audience text,
    team_size character varying(255),
    timeline character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    uuid uuid NOT NULL,
    vision text,
    work_type character varying(255),
    founder_id bigint NOT NULL,
    CONSTRAINT startups_commitment_type_check CHECK (((commitment_type)::text = ANY ((ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying, 'CONTRACT'::character varying, 'INTERNSHIP'::character varying])::text[]))),
    CONSTRAINT startups_stage_check CHECK (((stage)::text = ANY ((ARRAY['IDEA'::character varying, 'PROTOTYPE'::character varying, 'MVP'::character varying, 'EARLY_TRACTION'::character varying, 'GROWTH'::character varying, 'SCALING'::character varying])::text[]))),
    CONSTRAINT startups_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying])::text[]))),
    CONSTRAINT startups_work_type_check CHECK (((work_type)::text = ANY ((ARRAY['REMOTE'::character varying, 'HYBRID'::character varying, 'ONSITE'::character varying])::text[])))
);


ALTER TABLE public.startups OWNER TO postgres;

--
-- Name: startups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.startups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.startups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_education; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_education (
    user_profile_id bigint NOT NULL,
    education_entry character varying(255)
);


ALTER TABLE public.user_education OWNER TO postgres;

--
-- Name: user_experience; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_experience (
    user_profile_id bigint NOT NULL,
    experience_entry character varying(255)
);


ALTER TABLE public.user_experience OWNER TO postgres;

--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_profiles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    bio text,
    city character varying(100),
    company_name character varying(150),
    country character varying(100),
    cover_image_url character varying(255),
    date_of_birth date,
    gender character varying(20),
    github_url character varying(255),
    linkedin_url character varying(255),
    overview text,
    phone_number character varying(20),
    portfolio_url character varying(255),
    resume_url character varying(255),
    startup_name character varying(150),
    state character varying(100),
    website character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.user_profiles OWNER TO postgres;

--
-- Name: user_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_projects (
    user_profile_id bigint NOT NULL,
    project text
);


ALTER TABLE public.user_projects OWNER TO postgres;

--
-- Name: user_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_skills (
    user_profile_id bigint NOT NULL,
    skill character varying(255)
);


ALTER TABLE public.user_skills OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    account_locked_until timestamp(6) without time zone,
    account_status character varying(20) NOT NULL,
    clerk_id character varying(100),
    email character varying(100) NOT NULL,
    email_verified boolean NOT NULL,
    failed_login_attempts integer NOT NULL,
    full_name character varying(100) NOT NULL,
    last_login timestamp(6) without time zone,
    last_seen timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    presence_status character varying(20),
    profile_image character varying(255),
    role character varying(20) NOT NULL,
    username character varying(20),
    uuid uuid NOT NULL,
    CONSTRAINT users_account_status_check CHECK (((account_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PENDING'::character varying, 'LOCKED'::character varying, 'SUSPENDED'::character varying, 'DELETED'::character varying, 'DEACTIVATED'::character varying])::text[]))),
    CONSTRAINT users_presence_status_check CHECK (((presence_status)::text = ANY ((ARRAY['ONLINE'::character varying, 'OFFLINE'::character varying, 'BUSY'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'FOUNDER'::character varying, 'TALENT'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_activity_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspace_activity_logs (
    id bigint NOT NULL,
    action_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255) NOT NULL,
    uuid uuid NOT NULL,
    actor_id bigint,
    startup_id bigint NOT NULL
);


ALTER TABLE public.workspace_activity_logs OWNER TO postgres;

--
-- Name: workspace_activity_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspace_activity_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_activity_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_announcements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspace_announcements (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    pinned boolean NOT NULL,
    title character varying(255) NOT NULL,
    uuid uuid NOT NULL,
    author_id bigint NOT NULL,
    startup_id bigint NOT NULL
);


ALTER TABLE public.workspace_announcements OWNER TO postgres;

--
-- Name: workspace_announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspace_announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_calendar_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspace_calendar_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    end_date timestamp(6) without time zone NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL,
    uuid uuid NOT NULL,
    created_by_id bigint NOT NULL,
    startup_id bigint NOT NULL
);


ALTER TABLE public.workspace_calendar_events OWNER TO postgres;

--
-- Name: workspace_calendar_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspace_calendar_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_calendar_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspace_files (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    file_name character varying(255) NOT NULL,
    file_size bigint,
    file_type character varying(255) NOT NULL,
    file_url character varying(255) NOT NULL,
    folder_path character varying(255),
    uuid uuid NOT NULL,
    startup_id bigint NOT NULL,
    uploader_id bigint NOT NULL
);


ALTER TABLE public.workspace_files OWNER TO postgres;

--
-- Name: workspace_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspace_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspace_members (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    startup_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT workspace_members_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'TEAM_MEMBER'::character varying])::text[]))),
    CONSTRAINT workspace_members_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'REMOVED'::character varying, 'INVITED'::character varying])::text[])))
);


ALTER TABLE public.workspace_members OWNER TO postgres;

--
-- Name: workspace_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspace_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_roadmap_milestones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspace_roadmap_milestones (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    due_date timestamp(6) without time zone,
    progress integer NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid uuid NOT NULL,
    startup_id bigint NOT NULL
);


ALTER TABLE public.workspace_roadmap_milestones OWNER TO postgres;

--
-- Name: workspace_roadmap_milestones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspace_roadmap_milestones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_roadmap_milestones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workspace_tasks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    due_date timestamp(6) without time zone,
    priority character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid uuid NOT NULL,
    assignee_id bigint,
    reporter_id bigint NOT NULL,
    startup_id bigint NOT NULL,
    CONSTRAINT workspace_tasks_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT workspace_tasks_status_check CHECK (((status)::text = ANY ((ARRAY['BACKLOG'::character varying, 'TODO'::character varying, 'IN_PROGRESS'::character varying, 'REVIEW'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.workspace_tasks OWNER TO postgres;

--
-- Name: workspace_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workspace_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);


--
-- Name: application_status_history application_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_status_history
    ADD CONSTRAINT application_status_history_pkey PRIMARY KEY (id);


--
-- Name: call_analytics call_analytics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_analytics
    ADD CONSTRAINT call_analytics_pkey PRIMARY KEY (id);


--
-- Name: call_logs call_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_logs
    ADD CONSTRAINT call_logs_pkey PRIMARY KEY (id);


--
-- Name: chat_members chat_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_members
    ADD CONSTRAINT chat_members_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: chat_notifications chat_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_notifications
    ADD CONSTRAINT chat_notifications_pkey PRIMARY KEY (id);


--
-- Name: chat_rooms chat_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT chat_rooms_pkey PRIMARY KEY (id);


--
-- Name: chat_settings chat_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_settings
    ADD CONSTRAINT chat_settings_pkey PRIMARY KEY (id);


--
-- Name: custom_roles custom_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_roles
    ADD CONSTRAINT custom_roles_pkey PRIMARY KEY (id);


--
-- Name: startup_applications idx_application_uuid; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_applications
    ADD CONSTRAINT idx_application_uuid UNIQUE (uuid);


--
-- Name: job_offers idx_job_offer_uuid; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_offers
    ADD CONSTRAINT idx_job_offer_uuid UNIQUE (uuid);


--
-- Name: startups idx_startup_uuid; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startups
    ADD CONSTRAINT idx_startup_uuid UNIQUE (uuid);


--
-- Name: users idx_user_clerk_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_user_clerk_id UNIQUE (clerk_id);


--
-- Name: users idx_user_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_user_email UNIQUE (email);


--
-- Name: users idx_user_username; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_user_username UNIQUE (username);


--
-- Name: users idx_user_uuid; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_user_uuid UNIQUE (uuid);


--
-- Name: job_offers job_offers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_offers
    ADD CONSTRAINT job_offers_pkey PRIMARY KEY (id);


--
-- Name: meeting_chats meeting_chats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_chats
    ADD CONSTRAINT meeting_chats_pkey PRIMARY KEY (id);


--
-- Name: meeting_participants meeting_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT meeting_participants_pkey PRIMARY KEY (id);


--
-- Name: meetings meetings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);


--
-- Name: message_attachments message_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_attachments
    ADD CONSTRAINT message_attachments_pkey PRIMARY KEY (id);


--
-- Name: message_reactions message_reactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_reactions
    ADD CONSTRAINT message_reactions_pkey PRIMARY KEY (id);


--
-- Name: message_read_receipts message_read_receipts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_read_receipts
    ADD CONSTRAINT message_read_receipts_pkey PRIMARY KEY (id);


--
-- Name: message_statuses message_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_statuses
    ADD CONSTRAINT message_statuses_pkey PRIMARY KEY (id);


--
-- Name: privacy_settings privacy_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.privacy_settings
    ADD CONSTRAINT privacy_settings_pkey PRIMARY KEY (id);


--
-- Name: startup_applications startup_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_applications
    ADD CONSTRAINT startup_applications_pkey PRIMARY KEY (id);


--
-- Name: startup_attachments startup_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_attachments
    ADD CONSTRAINT startup_attachments_pkey PRIMARY KEY (id);


--
-- Name: startup_bookmarks startup_bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_bookmarks
    ADD CONSTRAINT startup_bookmarks_pkey PRIMARY KEY (id);


--
-- Name: startup_roles startup_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_roles
    ADD CONSTRAINT startup_roles_pkey PRIMARY KEY (id);


--
-- Name: startup_skills startup_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_skills
    ADD CONSTRAINT startup_skills_pkey PRIMARY KEY (id);


--
-- Name: startup_views startup_views_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_views
    ADD CONSTRAINT startup_views_pkey PRIMARY KEY (id);


--
-- Name: startups startups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startups
    ADD CONSTRAINT startups_pkey PRIMARY KEY (id);


--
-- Name: meetings uk30ay9npbnx4wxviiwe53rjf6h; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT uk30ay9npbnx4wxviiwe53rjf6h UNIQUE (uuid);


--
-- Name: meeting_chats uk3j4dqy6mc7rf4ww3h37sqnac8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_chats
    ADD CONSTRAINT uk3j4dqy6mc7rf4ww3h37sqnac8 UNIQUE (uuid);


--
-- Name: custom_roles uk3m5vi0l0okhfi1xvc3x0lylvs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_roles
    ADD CONSTRAINT uk3m5vi0l0okhfi1xvc3x0lylvs UNIQUE (uuid);


--
-- Name: chat_notifications uk59jfoer0dwqobr44iawl0mawe; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_notifications
    ADD CONSTRAINT uk59jfoer0dwqobr44iawl0mawe UNIQUE (uuid);


--
-- Name: chat_rooms uk5ldxl7bwlnhhwqfcb6proliyq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT uk5ldxl7bwlnhhwqfcb6proliyq UNIQUE (uuid);


--
-- Name: workspace_tasks uk72ylmbsay7y7yam6b31ybfal6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_tasks
    ADD CONSTRAINT uk72ylmbsay7y7yam6b31ybfal6 UNIQUE (uuid);


--
-- Name: privacy_settings uk8im8nq9irhhgjmw7pnfl2awu2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.privacy_settings
    ADD CONSTRAINT uk8im8nq9irhhgjmw7pnfl2awu2 UNIQUE (user_id);


--
-- Name: workspace_files uka67i4mbb01cv7a2b51dtnlpbp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_files
    ADD CONSTRAINT uka67i4mbb01cv7a2b51dtnlpbp UNIQUE (uuid);


--
-- Name: call_logs ukbgxhcc1pgf720lmkeav6746po; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_logs
    ADD CONSTRAINT ukbgxhcc1pgf720lmkeav6746po UNIQUE (uuid);


--
-- Name: call_analytics ukbnvaspjkaluikwrbolp4dd6jl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_analytics
    ADD CONSTRAINT ukbnvaspjkaluikwrbolp4dd6jl UNIQUE (call_log_id);


--
-- Name: announcements ukbxo6lbwqlp19q58ss0wuvyynd; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT ukbxo6lbwqlp19q58ss0wuvyynd UNIQUE (uuid);


--
-- Name: workspace_announcements ukcntrrod7nqh9on7nvxjnp3g8f; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_announcements
    ADD CONSTRAINT ukcntrrod7nqh9on7nvxjnp3g8f UNIQUE (uuid);


--
-- Name: message_read_receipts ukdqgj4b4kx1nqvwynje878nmby; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_read_receipts
    ADD CONSTRAINT ukdqgj4b4kx1nqvwynje878nmby UNIQUE (room_id, user_id);


--
-- Name: user_profiles uke5h89rk3ijvdmaiig4srogdc6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT uke5h89rk3ijvdmaiig4srogdc6 UNIQUE (user_id);


--
-- Name: workspace_calendar_events ukidftdb2xgdxkiq967d7o36fya; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_calendar_events
    ADD CONSTRAINT ukidftdb2xgdxkiq967d7o36fya UNIQUE (uuid);


--
-- Name: chat_messages ukihj91iuo2brr4io2h19t24m4k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT ukihj91iuo2brr4io2h19t24m4k UNIQUE (uuid);


--
-- Name: startups ukjsvq3jxex60o93ynaeus0bue6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startups
    ADD CONSTRAINT ukjsvq3jxex60o93ynaeus0bue6 UNIQUE (name, founder_id);


--
-- Name: startup_applications ukk00jofp80vo26cscy9xiax06f; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_applications
    ADD CONSTRAINT ukk00jofp80vo26cscy9xiax06f UNIQUE (user_id, startup_id);


--
-- Name: workspace_members ukk59ne75erxgafu1rrx6niihxc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT ukk59ne75erxgafu1rrx6niihxc UNIQUE (startup_id, user_id);


--
-- Name: workspace_activity_logs ukr7mpsuynexj1jxjcmrxu6jfus; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_activity_logs
    ADD CONSTRAINT ukr7mpsuynexj1jxjcmrxu6jfus UNIQUE (uuid);


--
-- Name: startup_bookmarks ukrh0yp98rygkfth0nxpl2hmbmv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_bookmarks
    ADD CONSTRAINT ukrh0yp98rygkfth0nxpl2hmbmv UNIQUE (user_id, startup_id);


--
-- Name: message_attachments ukrnada2vdbyned3dngsoe18sov; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_attachments
    ADD CONSTRAINT ukrnada2vdbyned3dngsoe18sov UNIQUE (uuid);


--
-- Name: job_offers ukryuvi5yh41suctqx91quxqt9o; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_offers
    ADD CONSTRAINT ukryuvi5yh41suctqx91quxqt9o UNIQUE (startup_id, talent_id);


--
-- Name: workspace_roadmap_milestones ukta8enpraypvfn4jpwmbuxglb1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_roadmap_milestones
    ADD CONSTRAINT ukta8enpraypvfn4jpwmbuxglb1 UNIQUE (uuid);


--
-- Name: chat_settings uktvvxtu3tct5njd2a9xnluy50; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_settings
    ADD CONSTRAINT uktvvxtu3tct5njd2a9xnluy50 UNIQUE (room_id);


--
-- Name: message_statuses ukxrirpqdmghxvnitjuoino10q; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_statuses
    ADD CONSTRAINT ukxrirpqdmghxvnitjuoino10q UNIQUE (message_id, user_id);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: workspace_activity_logs workspace_activity_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_activity_logs
    ADD CONSTRAINT workspace_activity_logs_pkey PRIMARY KEY (id);


--
-- Name: workspace_announcements workspace_announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_announcements
    ADD CONSTRAINT workspace_announcements_pkey PRIMARY KEY (id);


--
-- Name: workspace_calendar_events workspace_calendar_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_calendar_events
    ADD CONSTRAINT workspace_calendar_events_pkey PRIMARY KEY (id);


--
-- Name: workspace_files workspace_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_files
    ADD CONSTRAINT workspace_files_pkey PRIMARY KEY (id);


--
-- Name: workspace_members workspace_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT workspace_members_pkey PRIMARY KEY (id);


--
-- Name: workspace_roadmap_milestones workspace_roadmap_milestones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_roadmap_milestones
    ADD CONSTRAINT workspace_roadmap_milestones_pkey PRIMARY KEY (id);


--
-- Name: workspace_tasks workspace_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_tasks
    ADD CONSTRAINT workspace_tasks_pkey PRIMARY KEY (id);


--
-- Name: idx_application_startup; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_application_startup ON public.startup_applications USING btree (startup_id);


--
-- Name: idx_application_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_application_status ON public.startup_applications USING btree (status);


--
-- Name: idx_chat_member_room_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_member_room_id ON public.chat_members USING btree (room_id);


--
-- Name: idx_chat_member_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_member_user_id ON public.chat_members USING btree (user_id);


--
-- Name: idx_chat_msg_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_msg_created_at ON public.chat_messages USING btree (created_at);


--
-- Name: idx_chat_msg_room_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_msg_room_id ON public.chat_messages USING btree (room_id);


--
-- Name: idx_job_offer_founder; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_job_offer_founder ON public.job_offers USING btree (founder_id);


--
-- Name: idx_job_offer_startup; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_job_offer_startup ON public.job_offers USING btree (startup_id);


--
-- Name: idx_job_offer_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_job_offer_status ON public.job_offers USING btree (status);


--
-- Name: idx_job_offer_talent; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_job_offer_talent ON public.job_offers USING btree (talent_id);


--
-- Name: idx_message_status_message_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_message_status_message_id ON public.message_statuses USING btree (message_id);


--
-- Name: idx_message_status_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_message_status_user_id ON public.message_statuses USING btree (user_id);


--
-- Name: idx_msg_attach_message_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_msg_attach_message_id ON public.message_attachments USING btree (message_id);


--
-- Name: idx_startup_founder; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_startup_founder ON public.startups USING btree (founder_id);


--
-- Name: idx_startup_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_startup_status ON public.startups USING btree (status);


--
-- Name: idx_startup_views_user_startup_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_startup_views_user_startup_time ON public.startup_views USING btree (user_id, startup_id, created_at);


--
-- Name: idx_workspace_member_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_workspace_member_user ON public.workspace_members USING btree (user_id);


--
-- Name: chat_message_deletions fk125m75t3ta1wnx3lx1o5bnmq7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message_deletions
    ADD CONSTRAINT fk125m75t3ta1wnx3lx1o5bnmq7 FOREIGN KEY (message_id) REFERENCES public.chat_messages(id);


--
-- Name: announcements fk1pgl63iwbqvmngumhvr3xopg3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fk1pgl63iwbqvmngumhvr3xopg3 FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: chat_notifications fk2k13qcsrp7lmjpthqtei2q562; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_notifications
    ADD CONSTRAINT fk2k13qcsrp7lmjpthqtei2q562 FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: workspace_files fk2q1hc66988g1hhkk5g9x7n46w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_files
    ADD CONSTRAINT fk2q1hc66988g1hhkk5g9x7n46w FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: workspace_announcements fk3a7dtiy85f8e3jxoqnxvpwc4j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_announcements
    ADD CONSTRAINT fk3a7dtiy85f8e3jxoqnxvpwc4j FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: call_logs fk3b13vydabrtapsdesi09ysn61; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_logs
    ADD CONSTRAINT fk3b13vydabrtapsdesi09ysn61 FOREIGN KEY (workspace_id) REFERENCES public.startups(id);


--
-- Name: startup_attachments fk3bbxkw4obgdogdjgjyue6dxpi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_attachments
    ADD CONSTRAINT fk3bbxkw4obgdogdjgjyue6dxpi FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: startup_bookmarks fk3dh3luj52wuq5x2uebieesuvf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_bookmarks
    ADD CONSTRAINT fk3dh3luj52wuq5x2uebieesuvf FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: call_logs fk3m5t0cuvw1c00c9gac117ilr2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_logs
    ADD CONSTRAINT fk3m5t0cuvw1c00c9gac117ilr2 FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: call_log_deletions fk470agkocqte15u35ikblovjxf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_log_deletions
    ADD CONSTRAINT fk470agkocqte15u35ikblovjxf FOREIGN KEY (call_id) REFERENCES public.call_logs(id);


--
-- Name: meeting_participants fk47sc15ag6030wipkxxj0a1t8o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT fk47sc15ag6030wipkxxj0a1t8o FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chat_settings fk4e50cq6720hy8p47tmsuomfqm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_settings
    ADD CONSTRAINT fk4e50cq6720hy8p47tmsuomfqm FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id);


--
-- Name: job_offers fk56ey1n8dub0ryr9lvba3p97xj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_offers
    ADD CONSTRAINT fk56ey1n8dub0ryr9lvba3p97xj FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: user_experience fk692arnd9ftstx4puw68jrc7yq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_experience
    ADD CONSTRAINT fk692arnd9ftstx4puw68jrc7yq FOREIGN KEY (user_profile_id) REFERENCES public.user_profiles(id);


--
-- Name: workspace_members fk6vtnpc3eexk504u61uepn40p1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT fk6vtnpc3eexk504u61uepn40p1 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: workspace_tasks fk6wweyb1yiqstnjgm66ml8uof3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_tasks
    ADD CONSTRAINT fk6wweyb1yiqstnjgm66ml8uof3 FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: workspace_tasks fk71ip163qfs7ty6wrfm715ushe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_tasks
    ADD CONSTRAINT fk71ip163qfs7ty6wrfm715ushe FOREIGN KEY (assignee_id) REFERENCES public.users(id);


--
-- Name: workspace_calendar_events fk7arv68qvraadm3p628tfimlst; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_calendar_events
    ADD CONSTRAINT fk7arv68qvraadm3p628tfimlst FOREIGN KEY (created_by_id) REFERENCES public.users(id);


--
-- Name: meeting_participants fk7uds89kvog9etbdnn653vsf6y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_participants
    ADD CONSTRAINT fk7uds89kvog9etbdnn653vsf6y FOREIGN KEY (meeting_id) REFERENCES public.meetings(id);


--
-- Name: message_read_receipts fk8bn2wx4g7j3fedas8rb1cgbbp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_read_receipts
    ADD CONSTRAINT fk8bn2wx4g7j3fedas8rb1cgbbp FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id);


--
-- Name: workspace_members fk8ocasqs38esj8twdllkq0atws; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_members
    ADD CONSTRAINT fk8ocasqs38esj8twdllkq0atws FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: custom_roles fk8tjpiuidbry5slvdpru8ngdpp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_roles
    ADD CONSTRAINT fk8tjpiuidbry5slvdpru8ngdpp FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: startup_skills fk9h97nm0ghylrc51aqv5umg4l0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_skills
    ADD CONSTRAINT fk9h97nm0ghylrc51aqv5umg4l0 FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: workspace_files fk9hheli1ocgg3wukjbm7egl5eo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_files
    ADD CONSTRAINT fk9hheli1ocgg3wukjbm7egl5eo FOREIGN KEY (uploader_id) REFERENCES public.users(id);


--
-- Name: meetings fkaa1dp9oxlq8sykp2s8xwcshr7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fkaa1dp9oxlq8sykp2s8xwcshr7 FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: chat_notifications fkahj0o96f5hwnj0av6bm9snfp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_notifications
    ADD CONSTRAINT fkahj0o96f5hwnj0av6bm9snfp FOREIGN KEY (recipient_id) REFERENCES public.users(id);


--
-- Name: chat_messages fkbrvto53oo11ra25g8y5ynlojw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkbrvto53oo11ra25g8y5ynlojw FOREIGN KEY (reply_to_id) REFERENCES public.chat_messages(id);


--
-- Name: workspace_roadmap_milestones fkce5jb00gn6xl0xcwfo45vvtm4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_roadmap_milestones
    ADD CONSTRAINT fkce5jb00gn6xl0xcwfo45vvtm4 FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: workspace_activity_logs fkcevrqdkxewvj49p2gld9q4k68; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_activity_logs
    ADD CONSTRAINT fkcevrqdkxewvj49p2gld9q4k68 FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: startup_views fkcexccwomg2iwd66q4j6rybfq9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_views
    ADD CONSTRAINT fkcexccwomg2iwd66q4j6rybfq9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chat_rooms fkdhbk2vs32an669mdygvorqar2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT fkdhbk2vs32an669mdygvorqar2 FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: chat_members fke0a4ocat8hcxc20kt2m95qejk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_members
    ADD CONSTRAINT fke0a4ocat8hcxc20kt2m95qejk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: meeting_chats fke32u1wtkir2dxy9cmo9kb9x5j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_chats
    ADD CONSTRAINT fke32u1wtkir2dxy9cmo9kb9x5j FOREIGN KEY (meeting_id) REFERENCES public.meetings(id);


--
-- Name: workspace_calendar_events fkecql9nxfw9e1uc8keq8yjjg5u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_calendar_events
    ADD CONSTRAINT fkecql9nxfw9e1uc8keq8yjjg5u FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: user_skills fkem4jmtpyq4lkqenj9osdmyaoy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_skills
    ADD CONSTRAINT fkem4jmtpyq4lkqenj9osdmyaoy FOREIGN KEY (user_profile_id) REFERENCES public.user_profiles(id);


--
-- Name: message_statuses fkepys2y8ca97594ptrvkuriblc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_statuses
    ADD CONSTRAINT fkepys2y8ca97594ptrvkuriblc FOREIGN KEY (message_id) REFERENCES public.chat_messages(id);


--
-- Name: call_logs fkfaw5ddta8c71u5q5jevqay0a8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_logs
    ADD CONSTRAINT fkfaw5ddta8c71u5q5jevqay0a8 FOREIGN KEY (caller_id) REFERENCES public.users(id);


--
-- Name: application_status_history fkfb625atilolbfug9sqxe9xbt1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_status_history
    ADD CONSTRAINT fkfb625atilolbfug9sqxe9xbt1 FOREIGN KEY (changed_by_user_id) REFERENCES public.users(id);


--
-- Name: announcements fkffciqkf0nxy8qakyqn54lwm2d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fkffciqkf0nxy8qakyqn54lwm2d FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: role_permissions fkfhm3m0e7va24sp8xfh73cf4ht; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkfhm3m0e7va24sp8xfh73cf4ht FOREIGN KEY (role_id) REFERENCES public.custom_roles(id);


--
-- Name: message_statuses fkfr5vxt8u6eopfvl93b9r2r8m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_statuses
    ADD CONSTRAINT fkfr5vxt8u6eopfvl93b9r2r8m FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: message_read_receipts fkfws1llgb2i066i1mebldx48d1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_read_receipts
    ADD CONSTRAINT fkfws1llgb2i066i1mebldx48d1 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chat_messages fkgiqeap8ays4lf684x7m0r2729; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkgiqeap8ays4lf684x7m0r2729 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: privacy_settings fkgxn6jq4rudo7ss3lmrg5avkh6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.privacy_settings
    ADD CONSTRAINT fkgxn6jq4rudo7ss3lmrg5avkh6 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chat_notifications fkh30xdq6m4xu6mhdcuvwopl8gb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_notifications
    ADD CONSTRAINT fkh30xdq6m4xu6mhdcuvwopl8gb FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id);


--
-- Name: chat_messages fkhalwepod3944695ji0suwoqb9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkhalwepod3944695ji0suwoqb9 FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id);


--
-- Name: application_status_history fkhne29h0j56go3xrtu8o3vy41q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application_status_history
    ADD CONSTRAINT fkhne29h0j56go3xrtu8o3vy41q FOREIGN KEY (application_id) REFERENCES public.startup_applications(id);


--
-- Name: user_education fki0pk7crv49qftdcls4yqsuc8r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_education
    ADD CONSTRAINT fki0pk7crv49qftdcls4yqsuc8r FOREIGN KEY (user_profile_id) REFERENCES public.user_profiles(id);


--
-- Name: startup_applications fkieue4m8xdn9s2splbwcpy531y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_applications
    ADD CONSTRAINT fkieue4m8xdn9s2splbwcpy531y FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: workspace_tasks fkj262qak22a388yfmbbjedsavp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_tasks
    ADD CONSTRAINT fkj262qak22a388yfmbbjedsavp FOREIGN KEY (reporter_id) REFERENCES public.users(id);


--
-- Name: user_profiles fkjcad5nfve11khsnpwj1mv8frj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT fkjcad5nfve11khsnpwj1mv8frj FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: call_analytics fkju81w36lx6pjvbvbyi2hogs1i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_analytics
    ADD CONSTRAINT fkju81w36lx6pjvbvbyi2hogs1i FOREIGN KEY (call_log_id) REFERENCES public.call_logs(id);


--
-- Name: user_projects fkkxkgtcs9iyducrsvem4bo1blu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_projects
    ADD CONSTRAINT fkkxkgtcs9iyducrsvem4bo1blu FOREIGN KEY (user_profile_id) REFERENCES public.user_profiles(id);


--
-- Name: message_reactions fkl0wgr4m59s18ykhnsp6a55icw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_reactions
    ADD CONSTRAINT fkl0wgr4m59s18ykhnsp6a55icw FOREIGN KEY (message_id) REFERENCES public.chat_messages(id);


--
-- Name: job_offers fkl3gvr7ggxqn3h88p3bxxc7fyd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_offers
    ADD CONSTRAINT fkl3gvr7ggxqn3h88p3bxxc7fyd FOREIGN KEY (talent_id) REFERENCES public.users(id);


--
-- Name: startup_applications fkl7yjs65s12v0x8hur400xhrqu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_applications
    ADD CONSTRAINT fkl7yjs65s12v0x8hur400xhrqu FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: message_read_receipts fklbhkk8isybb71l08p1y2jnvhr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_read_receipts
    ADD CONSTRAINT fklbhkk8isybb71l08p1y2jnvhr FOREIGN KEY (last_read_message_id) REFERENCES public.chat_messages(id);


--
-- Name: job_offers fkle5emcgmmi7dnx33u2jd1uvgx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_offers
    ADD CONSTRAINT fkle5emcgmmi7dnx33u2jd1uvgx FOREIGN KEY (founder_id) REFERENCES public.users(id);


--
-- Name: startup_bookmarks fklnjd8xm3tpgic9b57911q1s4e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_bookmarks
    ADD CONSTRAINT fklnjd8xm3tpgic9b57911q1s4e FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: chat_notifications fkm70c2dri7dsea2ys9xqh691nh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_notifications
    ADD CONSTRAINT fkm70c2dri7dsea2ys9xqh691nh FOREIGN KEY (message_id) REFERENCES public.chat_messages(id);


--
-- Name: message_attachments fkm7tu5b64a3vv20ikbf8wul8sv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_attachments
    ADD CONSTRAINT fkm7tu5b64a3vv20ikbf8wul8sv FOREIGN KEY (message_id) REFERENCES public.chat_messages(id);


--
-- Name: workspace_announcements fkn5vuyvfpf237flypvd04n5dy3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_announcements
    ADD CONSTRAINT fkn5vuyvfpf237flypvd04n5dy3 FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: workspace_activity_logs fknkwsiwdoxyaonpqd6d4c9s1kd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workspace_activity_logs
    ADD CONSTRAINT fknkwsiwdoxyaonpqd6d4c9s1kd FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: meeting_chats fknntxvwxo15bo13pwl2dpam665; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_chats
    ADD CONSTRAINT fknntxvwxo15bo13pwl2dpam665 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: startup_views fkntl9rnruy1mmfpfp1m68k22m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_views
    ADD CONSTRAINT fkntl9rnruy1mmfpfp1m68k22m FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: message_reactions fkoip2ttlg2py976foointttaew; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_reactions
    ADD CONSTRAINT fkoip2ttlg2py976foointttaew FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: chat_members fkoww5qci3v6n6dxqmbwte0rdbn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_members
    ADD CONSTRAINT fkoww5qci3v6n6dxqmbwte0rdbn FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id);


--
-- Name: startups fkpvsm0wjj3kuk4b3n1il42gcwy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startups
    ADD CONSTRAINT fkpvsm0wjj3kuk4b3n1il42gcwy FOREIGN KEY (founder_id) REFERENCES public.users(id);


--
-- Name: startup_roles fkr1hmnx1iws5y6qetyjtuyw41t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.startup_roles
    ADD CONSTRAINT fkr1hmnx1iws5y6qetyjtuyw41t FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: chat_notifications fkrt5qqxaswkmkf8pex7155jff2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_notifications
    ADD CONSTRAINT fkrt5qqxaswkmkf8pex7155jff2 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: meetings fkt5scbte6s2htui1wr5xqygp9p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT fkt5scbte6s2htui1wr5xqygp9p FOREIGN KEY (startup_id) REFERENCES public.startups(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict daO011BmuzbO6RJ6BnAj5esd1LEKjZgIDcaPXRDbkNRDsEH2i5jlp2FvKR1aSFk

